import type { ArticleContent } from "./types";

export const article: ArticleContent = {
  slug: "tumores-hipofisarios",
  sections: [
    {
      id: "definicao",
      heading: "Definição",
      paragraphs: [
        "A região do crânio denominada selar compreende a sela turca ou sela túrcica, estrutura óssea em forma de sela, ou manjedoura, ou berço, dentro da qual encontra-se a glândula Hipófise. A glândula hipófise, também chamada glândula pituitária ou glândula mestra, é assim chamada tendo em vista sua enorme importância uma vez que produz ou armazena a maioria dos hormônios envolvidos no perfeito funcionamento do corpo humano. Os tumores da região selar compreendem principalmente os adenomas hipofisários, craniofaringeomas e meningeomas. São também encontrados nessa região cistos aracnóides, germinomas, hamartomas e cistos da fissura de Rathke. Os tumores hipofisários são divididos em tumores secretores e não secretores de hormônios. Quanto ao seu tamanho, são divididos em microadenomas, quando menores que 1 cm e macroadenomas, quando maiores que 1 cm. Quanto aos sintomas apresentados pelos portadores de tal doença, eles são dependentes das características do tumor. Quando trata-se de microadenomas. Os tumores são assintomáticos, quando não secretores. Quando os tumores secretam hormônios, os sintomas variam dependendo das características do hormônio secretado em excesso. Quando os tumores são maiores de 1 cm, os macroadenomas, os sintomas são decorrentes não só dos hormônios secretados, quando os tumores são secretores, mas também do aumento de volume tumoral com compressão de estruturas neurovasculares adjacentes ao tumor, mesmo quando trata-se de tumores não secretores de hormônios. Cefaléia (dor de cabeça) e alterações visuais por compressão tumoral dos nervos ópticos (visuais) são os sintomas mais comuns. Em alguns casos, ocorre hemorragia tumoral, chamada de apoplexia hipofisária. Esses casos compreendem grande gravidade pelo aumento imediato da pressão dentro da sela túrcica com potencial distúrbio hormonal grave podendo evoluir a perda da visão por compressão dos nervos ou quiasma óptico. O diagnóstico é realizado através da ressonância magnética para identificação da massa tumoral e do estudo dos hormônios do eixo hipotálamo-hipofisário. A tomografia computadorizada dos seios da face pode ser utilizada para programação do acesso cirúrgico. O tratamento preferencialmente é realizado mediante acesso trans-nasal endoscópico à região selar, com ressecção microcirúrgica da lesão tumoral, seja o macroadenoma ou o microadenoma secretor de hormônios. Mediante existência de grande voluma tumoral, com extensão para-selar (lateralmente a sela túrcica), supra-selar e compressão de estruturas cerebrais, o neurocirurgião pode optar por um acesso trans-craniano para ressecção dos tumores hipofisários e demais tumores da região selar como citados anteriormente.",
      ],
    },
  ],
};
